project_id = "njpscabswqgkujtevjim"

[functions.loyverse-sync]
verify_jwt = false

[functions.loyverse-config]
verify_jwt = false

[functions.loyverse-create-receipt]
verify_jwt = false

[functions.loyverse-purchase-request]
verify_jwt = false

[functions.loyverse-payments]
verify_jwt = false

[functions.telegram-notify]
verify_jwt = false

[functions.google-sheets-sync]
verify_jwt = false

[functions.loyverse-history-sync]
verify_jwt = false
